apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: review-test-pull
  janus-idp.io/tekton: review-test-pull
  backstage.io/kubernetes-id: review-test-pull
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: review-test-pull
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
